zanimaux_homepage:
    path:     /
    defaults: { _controller: ZanimauxBundle:Default:index }

affiche:
    path:     /affiche
    defaults: { _controller: ZanimauxBundle:Vet:affiche}
inscription:
    path:     /inscrit
    defaults: { _controller: ZanimauxBundle:User:inscrit }
modification:
    path:     /update
    defaults: { _controller: ZanimauxBundle:Vet:update }




